---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  vars:
    new_user: ansible_user
    keys_file: support.keys

  tasks:
    - set_fact:
        ssh_keys: "{{ lookup('file', 'ssh_keys/{{ keys_file }}').splitlines() }}"
    - debug:
        var: ssh_keys

    - name: add ssh keys for user "{{ new_user }}"
      lineinfile:
        dest: /home/{{ new_user }}/.ssh/authorized_keys
        state: present
        regexp: "{{ item }}"
        line: "{{ item }} "
      with_items:
        - "{{ ssh_keys }}"
